fix unicode-with version
Fix this error while building:

error: failed to select a version for `unicode-width` (required by `clap`):
all possible versions conflict with previously selected versions of `unicode-width`
  version 0.1.3 in use by unicode-width v0.1.3
  possible versions to select: 0.1.4